### ISSUE TITLE
canvas: error while reading from input stream

### ISSUE THREAD

**Issue by jomo** [crafatar/crafatar#147]
This happens extremely rarely, but does occur at times.
```
ERROR: Error: error while reading from input stream
ERROR:     at Error (native)
ERROR:     at Image.src (node_modules/canvas/lib/image.js:29:17)
ERROR:     at Object.exp.draw_model (lib/renders.js:195:13)
ERROR:     at lib/helpers.js:338:17
ERROR:     at FSReqWrap.cb [as oncomplete] (fs.js:212:19)
 INFO: GET /renders/body/ee1b30ed-336f-4003-b197-f6fc622260dd.png?helm&scale=3 500 132ms (server error)
```
The error is coming from [canvas/lib/image.js:29](https://github.com/Automattic/node-canvas/blob/eb97ef838658ee7a9cafb44bb20f3253e044e42b/lib/image.js#L29):
```js
Image.prototype.__defineSetter__('src', function(val){
  if ('string' == typeof val && 0 == val.indexOf('data:')) {
    val = val.slice(val.indexOf(',') + 1);
    this.source = new Buffer(val, 'base64');
  } else {
    this.source = val; // <------ here
  }
});
```
The actual 'native' error is `CAIRO_STATUS_READ_ERROR` which is coming from [somewhere inside canvas' Image.cc](https://github.com/Automattic/node-canvas/search?utf8=%E2%9C%93&q=CAIRO_STATUS_READ_ERROR), I guess that would be the one in [Image::SetSource](https://github.com/Automattic/node-canvas/blob/5405e73d29c0da59817ba30a390c5f98145949a4/src/Image.cc#L184):

```c++
Nan::SetAccessor(proto, Nan::New("source").ToLocalChecked(), GetSource, SetSource);
// ...
// lots of code
// ...
NAN_SETTER(Image::SetSource) {
  Image *img = Nan::ObjectWrap::Unwrap<Image>(info.This());
  cairo_status_t status = CAIRO_STATUS_READ_ERROR;

  img->clearData();

  // url string
  if (value->IsString()) {
    String::Utf8Value src(value);
    if (img->filename) free(img->filename);
    img->filename = strdup(*src);
    status = img->load();
  // Buffer
  } else if (Buffer::HasInstance(value)) {
    uint8_t *buf = (uint8_t *) Buffer::Data(value->ToObject());
    unsigned len = Buffer::Length(value->ToObject());
    status = img->loadFromBuffer(buf, len);
  }

  // check status
  if (status) {
    img->error(Canvas::Error(status));
  } else {
    img->loaded();
  }
}
```

I'm no C++ ninja, but it seems quite obvious that the error is returned when the `value` is neither a string nor an instance of `Buffer`.

We call `renders.draw_model` either when we render a default image or when we use a freshly downloaded image. Looking at server logs, the latter seems to be the case here.

There is an open issue about this error at https://github.com/Automattic/node-canvas/issues/364 that occurs when a JPEG is passed instead of a PNG.

I noticed that [we do](https://github.com/crafatar/crafatar/commit/288657107e0ce15f9d50de0b3be6236da0454629#diff-1) use `skins.save_image` to [strip meta tags / compress the image](https://github.com/crafatar/crafatar/issues/121), but the result is not part of the callback, so we just [use the image returned by the server](https://github.com/crafatar/crafatar/blob/c8d74d47be813dd069aff506664505ed67e7c710/lib/networking.js#L196-L201) which [might be anything but a PNG](https://github.com/crafatar/crafatar/issues/141). **This is a bug that should be fixed!**

However, we would still see the error thrown by lwip if it couldn't parse the image instead of the invalid image making its way to canvas. Besides, canvas has no problem to use JPEG as image source.
There is another image at https://github.com/Automattic/node-canvas/issues/122, but the issue linked above as well as this one seem to throw the error somewhere else (i.e. not at `Image::SetSource`) and they're either dependency/programming problems, or they're reproducible.

There are a few more things that lead to more confusion:

- I'm unable to reproduce this error (issuing the same request again works just fine)
- In this case, the same *skin* was requested once as render (via UUID) and once as avatar (via username). That means we did not make use of our simultaneous requests queuing (**We should do this for outgoing requests, too!**)
- The second (avatar) request was `downloaded` and served perfectly fine
- The requested skin is a perfectly valid PNG image (at least when I tried it)
- No errors coming from lwip
- The error _(should?)_ only occur when the image is not a `Buffer` _(nor string)_

The only thing I can think of that might be causing trouble is that the same skin was requested via UUID and name at the same time, which *might* have the effect of the skin image file being written twice at the same time. That would explain why it happens so rarely, but wouldn't explain anything else, since we don't use the skin file for rendering.
I could also imagine that Mojang's server returns errors or other crazy stuff at rare conditions, which might be a reason for `request` to give us something other than a Buffer (although I think it always returns a Buffer unless asked not to), but – again – we'd see errors from lwip and probably warnings from the `networking` module, too.

At this point I'm completely out of ideas, other than this being a bug in `node-canvas` or even Cairo.
Any other ideas what would cause this, or at least how to reproduce it?

**Comment by jomo** [comment]
Found another one where there were actually two different UUIDs
- `5fc215bd-8306-4396-971a-5670ff2a6529`
- `4374362b-e8f3-43eb-8311-11db5b109fac`

However, both share the [same skin](http://textures.minecraft.net/texture/4f4e479f9d6d56de4bb75a957719903e212d17b3b90ac25ddddf74f728219).

I used [crafatar/mojang_fake_api](https://github.com/crafatar/mojang_fake_api) to always return that texture URL (but I still used Mojang's texture server to actually download it). I then tried to reproduce the issue:
```Shell
while true; do
  curl -I "http://127.0.0.1:3000/renders/body/5fc215bd-8306-4396-971a-5670ff2a6529.png" &
    curl -I "http://127.0.0.1:3000/renders/body/4374362b-e8f3-43eb-8311-11db5b109fac.png"
  fg
  redis-cli flushall
  rm -f images/*/*
done
```

I was able to reproduce it a few times after running it for several minutes.
I still don't have anything useful, but at least here's the (slightly modified) log with debug enabled:
```
000ms: ----- HEAD /renders/body/5fc215bd-8306-4396-971a-5670ff2a6529.png
001ms: ----- userId not cached
003ms: +++++ HEAD /renders/body/4374362b-e8f3-43eb-8311-11db5b109fac.png
003ms: +++++ userId not cached
005ms: ----- http://127.0.0.1:5000/session/minecraft/profile/5fc215bd83064396971a5670ff2a6529 200 OK
006ms: ----- new skin hash: 4f4e479f9d6d56de4bb75a957719903e212d17b3b90ac25ddddf74f728219
006ms: ----- caching skin:undefined cape:null
008ms: +++++ http://127.0.0.1:5000/session/minecraft/profile/4374362be8f343eb831111db5b109fac 200 OK
009ms: +++++ new skin hash: 4f4e479f9d6d56de4bb75a957719903e212d17b3b90ac25ddddf74f728219
009ms: +++++ caching skin:undefined cape:null
514ms: +++++ http://textures.minecraft.net/texture/4f4e479f9d6d56de4bb75a957719903e212d17b3b90ac25ddddf74f728219 200 OK
534ms: +++++ face extracted
541ms: +++++ helm extracted
541ms: +++++ images/helms/4f4e479f9d6d56de4bb75a957719903e212d17b3b90ac25ddddf74f728219.png
541ms: +++++ caching skin:4f4e479f9d6d56de4bb75a957719903e212d17b3b90ac25ddddf74f728219 cape:undefined
544ms: +++++ cached hash:
545ms: +++++ new hash: 4f4e479f9d6d56de4bb75a957719903e212d17b3b90ac25ddddf74f728219
548ms: ----- http://textures.minecraft.net/texture/4f4e479f9d6d56de4bb75a957719903e212d17b3b90ac25ddddf74f728219 200 OK
550ms: +++++ skin already exists, not downloading
558ms: +++++ image not found, using default.
583ms: +++++ uses new skin format
588ms: ----- face extracted
592ms: ----- helm extracted
592ms: ----- images/helms/4f4e479f9d6d56de4bb75a957719903e212d17b3b90ac25ddddf74f728219.png
592ms: ----- caching skin:4f4e479f9d6d56de4bb75a957719903e212d17b3b90ac25ddddf74f728219 cape:undefined
592ms: ----- cached hash:
592ms: ----- new hash: 4f4e479f9d6d56de4bb75a957719903e212d17b3b90ac25ddddf74f728219
593ms: ----- skin already exists, not downloading
610ms: ----- uses new skin format
618ms: +++++ Error: error while reading from input stream
618ms: +++++    at Error (native)
618ms: +++++    at Image.src (node_modules/canvas/lib/image.js:29:17)
618ms: +++++    at Object.exp.draw_model (lib/renders.js:195:13)
618ms: +++++    at lib/helpers.js:338:17
618ms: +++++    at FSReqWrap.cb [as oncomplete] (fs.js:212:19)
619ms: +++++ HEAD /renders/body/4374362b-e8f3-43eb-8311-11db5b109fac.png 500 611ms (server error)
624ms: ----- HEAD /renders/body/5fc215bd-8306-4396-971a-5670ff2a6529.png 200 623ms (downloaded)
```

So it's definitely caused by something requesting the same texture at the same time.
Also both requests download the skin and *then* claim `skin already exists, not downloading`, that *might* be an issue with logging, though. Will look into that later.

**Comment by jomo** [comment]
I started logging the Buffer type + length:
```js
exp.draw_model = function(rid, img, scale, helm, body, callback) {
  var image = new Image();

  // ...

  logging.debug(rid, "typeof img", typeof img);
  logging.debug(rid, "img.constructor", img.constructor.name);
  logging.debug(rid, "img.length", img.length);

  if (!Buffer.isBuffer(img)) {
    logging.debug(img.toString());
    throw new Error("Not a Buffer!");
  }

  image.src = img;
}
```
and found this weird stuff (note: that is from a single request)
```
HEAD /renders/body/5fc215bd-8306-4396-971a-5670ff2a6529.png
userId not cached
http://127.0.0.1:5000/session/minecraft/profile/5fc215bd83064396971a5670ff2a6529 200 OK
new skin hash: 4f4e479f9d6d56de4bb75a957719903e212d17b3b90ac25ddddf74f728219
caching skin:undefined cape:null
http://textures.minecraft.net/texture/4f4e479f9d6d56de4bb75a957719903e212d17b3b90ac25ddddf74f728219 200 OK
face extracted
helm extracted
images/helms/4f4e479f9d6d56de4bb75a957719903e212d17b3b90ac25ddddf74f728219.png
caching skin:4f4e479f9d6d56de4bb75a957719903e212d17b3b90ac25ddddf74f728219 cape:undefined
cached hash:
new hash: 4f4e479f9d6d56de4bb75a957719903e212d17b3b90ac25ddddf74f728219

# everything ok until now

skin already exists, not downloading
typeof img object
img.constructor Buffer
img.length 0
image not found, using default.
typeof img object
img.constructor Buffer
img.length 997
uses new skin format
Error: error while reading from input stream
    at Error (native)
    at Image.src (node_modules/canvas/lib/image.js:29:17)
    at Object.exp.draw_model (lib/renders.js:202:13)
    at lib/helpers.js:338:17
    at FSReqWrap.cb [as oncomplete] (fs.js:212:19)
HEAD /renders/body/5fc215bd-8306-4396-971a-5670ff2a6529.png 500 281ms (server error)
```

So for some fucked up reason, `renders.draw_model` is called once with an empty Buffer and then **again** (!!) with a Buffer of 997 bytes. The right length would have been 4856 bytes.

**Comment by jomo** [comment]
> some fucked up reason

nvm :see_no_evil:
> image not found, using default.

And the `mhf_alex_skin.png` file is exactly `997` bytes. All good so far :+1: 

But this
> uses new skin format

still doesn't make _any_ sense. That log is coming from `renders.draw_body` which is called in the `image.onload` function.

So apparently it is **not** thrown in `Image::SetSource`, but at some later point instead. All other occurrences of `CAIRO_STATUS_READ_ERROR` don't seem to make any sense, though :sob:

Will continue debugging some time.

*/quit ragequit*

**Comment by jomo** [comment]
After thinking about it a little, it does actually make some sense.

The error is thrown when `image.src` is set to an empty buffer, but it's logged much later. All the other log between `img.length 0` and the error is just log coming from a default skin being rendered.

Now we only have to find out how the empty buffer gets there, because [we do check for empty replies](https://github.com/crafatar/crafatar/blob/7714e0e0ef3a6554d8e8d3b1302b6497d872c4c4/lib/networking.js#L106-L109).

----

whew! :relieved: :sleeping:

**Comment by jredfox** [comment]
uuid isn't stripped: 4374362b-e8f3-43eb-8311-11db5b109fac.png and there is a png this doesn't seem to work with craftar try striping the uuid and  removing the png
